---
proxy-providers:
   SINGAPORE:
    type: file
    path: "./proxy_provider/SG.yaml"
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 120
   INDONESIA:
    type: file
    path: "./proxy_provider/ID.yaml"
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 120
proxy-groups:
- name: LOADBALANCE
  type: load-balance
  strategy: round-robin
  disable-udp: false
  url: http://cp.cloudflare.com/generate_204
  interval: '60'
  use:
  - SINGAPORE
  - INDONESIA
- name: FALLBACK
  type: fallback
  disable-udp: false
  url: http://cp.cloudflare.com/generate_204
  interval: '60'
  tolerance: '120'
  use:
  - INDONESIA
- name: URL-TEST
  type: url-test
  disable-udp: false
  use:
  - SINGAPORE
  - INDONESIA
  url: http://cp.cloudflare.com/generate_204
  interval: '60'
- name: GEMING
  type: select
  disable-udp: false
  proxies:
  - URL-TEST
  - LOADBALANCE
  - FALLBACK
- name: STRIMING
  type: select
  disable-udp: false
  proxies:
  - URL-TEST
  - LOADBALANCE
  - FALLBACK
- name: SPEEDTEST
  type: select
  disable-udp: false
  proxies:
  - URL-TEST
  - LOADBALANCE
  - FALLBACK
- name: OLSHOP
  type: select
  disable-udp: false
  use:
  - INDONESIA
  url: https://cp.cloudflare.com/generate_204
  interval: '60'
- name: BANK
  type: select
  disable-udp: false
  use:
  - INDONESIA
  url: https://cp.cloudflare.com/generate_204
  interval: '60'
rule-providers:
  rule_speedtest:
    type: file
    behavior: classical
    path: "./rule_provider/speedtest.yaml"
  rule_striming:
    type: file
    behavior: classical
    path: "./rule_provider/striming.yaml"
  rule_gems:
    type: file
    behavior: domain
    path: "./rule_provider/gems.yaml"
  rule_gemsport:
    type: file
    behavior: classical
    path: "./rule_provider/gamsport.yaml"
  rule_bank:
    type: file
    behavior: classical
    path: "./rule_provider/bank.yaml"
  rule_olshop:
    type: file
    behavior: classical
    path: "./rule_provider/olshop.yaml"
  rule_nsfw:
    type: file
    behavior: domain
    path: "./rule_provider/nsfw.yaml"
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: fbrn02
bind-address: "*"
unified-delay: true
external-ui: "/usr/share/openclash/ui"
experimental:
  ignore-resolve-fail: true
ipv6: false
tun:
  enable: true
  stack: system
  device: utun
  mtu: 65535
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
profile:
  store-selected: true
  store-fakeip: true
  store-fake-ip: false
rules:
- DST-PORT,3478,GLOBAL
- RULE-SET,rule_gems,GEMING
- RULE-SET,rule_olshop,OLSHOP
- RULE-SET,rule_bank,BANK
- RULE-SET,rule_gemsport,GEMING
- RULE-SET,rule_striming,STRIMING
- RULE-SET,rule_nsfw,STRIMING
- RULE-SET,rule_speedtest,SPEEDTEST
- MATCH,GLOBAL
